version: '3.8'

# Simple ML components setup for integration
# Uma can extend this for full deployment infrastructure

services:
  # DeepFlyer ML Components Only
  deepflyer-ml:
    build: 
      context: .
      dockerfile: Dockerfile.ml
    environment:
      - PYTHONPATH=/deepflyer
    volumes:
      - ./weights:/deepflyer/weights:ro
      - ./logs:/deepflyer/logs
    # Note: Uma will add proper networking and deployment config

  # Optional: ClearML for ML experiment tracking (Ahmad's domain)
  clearml-ml:
    image: allegroai/clearml:latest
    ports:
      - "8080:8080"
    environment:
      - CLEARML_SERVER_HOST=http://localhost:8008
    volumes:
      - clearml_data:/opt/clearml/data
    # This is just for ML experiment tracking

volumes:
  clearml_data:

# Note for teammates:
# - Jay: Add your backend API service here
# - Uma: Add Gazebo, ROS2 bridge, and infrastructure services 